spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
      - optional:file:../../.env[.properties]
      - optional:file:back_end/Back_end/.env[.properties]
  application:
    name: back-end
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: ${MAIL_PROTOCOL:smtp}
    test-connection: ${MAIL_TEST_CONNECTION:false}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_STARTTLS_ENABLE:true}
            required: ${MAIL_STARTTLS_REQUIRED:true}
          ssl:
            enable: ${MAIL_SSL_ENABLE:false}
            trust: ${MAIL_SSL_TRUST:smtp.gmail.com}
          connectiontimeout: ${MAIL_CONNECTION_TIMEOUT:20000}
          timeout: ${MAIL_TIMEOUT:20000}
          writetimeout: ${MAIL_WRITE_TIMEOUT:20000}
server:
  port: 8080
  forward-headers-strategy: FRAMEWORK
jwt:
  secretKey: ${JWT_SECRET_KEY}
  accessTokenExpiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refreshTokenExpiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
